# coding=utf-8
"""
Test data in flattened package dictionary format.
"""

TEST_DATA_FLATTENED = {('_ckan_phase',): u'',
                       ('access_application_URL',): u'',
                       ('access_request_URL',): u'',
                       ('accept-terms',): u'yes',
                       ('agent', 0, 'URL'): u'',
                       ('agent', 0, 'fundingid'): u'',
                       ('agent', 0, 'name'): u'',
                       ('agent', 0, 'organisation'): u'',
                       ('agent', 0, 'role'): u'funder',
                       ('agent', 1, 'name'): u'dada',
                       ('agent', 1, 'role'): u'owner',
                       ('agent', 2, 'name'): u'dada',
                       ('agent', 2, 'organisation'): u'dada',
                       ('agent', 2, 'role'): u'author',
                       ('algorithm',): u'',
                       ('availability',): u'contact_owner',
                       ('checksum',): u'',
                       ('contact', 0, 'URL'): u'http://google.com',
                       ('contact', 0, 'email'): u'kata.selenium@gmail.com',
                       ('contact', 0, 'name'): u'dada',
                       ('contact', 0, 'phone'): u'+35805050505',
                       ('direct_download_URL',): u'',
                       ('discipline',): u'',
                       ('event', 1, 'descr'): u'',
                       ('event', 1, 'type'): u'collection',
                       ('event', 1, 'when'): u'',
                       ('event', 1, 'who'): u'',
                       ('format',): u'',
                       ('geographic_coverage',): u'',
                       ('langtitle', 0, 'lang'): u'sv',
                       ('langtitle', 0, 'value'): u'dada',
                       ('language',): u'swe',
                       ('license_id',): u'notspecified',
                       ('license_URL',): u'',
                       ('mimetype',): u'',
                       ('name',): u'',
                       ('new_version_pid',): u'',
                       ('notes',): u'',
                       ('pids', 0, 'id'): u'urn:nbn:fi:csc-kata20140728095757755621',
                       ('pids', 0, 'type'): u'data',
                       ('pids', 0, 'primary'): u'True',
                       ('pids', 1, 'id'): u'123456789ABC',
                       ('pids', 1, 'type'): u'metadata',
                       ('pids', 2, 'id'): u'ABCDEFG',
                       ('pids', 2, 'type'): u'data',
                       ('pkg_name',): u'',
                       ('save',): u'finish',
                       ('tag_string',): u'dada',
                       ('temporal_coverage_begin',): u'',
                       ('temporal_coverage_end',): u'',
                       ('version',): u'2014-05-16T05:58:49Z'
                      }