# coding: utf-8
tieteet = [{'description': u'Matematiikka',
  'name': u'Matematiikka',
  'title': u'Matematiikka'},
 {'description': u'Tilastotiede',
  'name': u'Tilastotiede',
  'title': u'Tilastotiede'},
 {'description': u'Tietojenkäsittely ja informaatiotieteet',
  'name': u'Tietojenkäsittely ja informaatiotieteet',
  'title': u'Tietojenkäsittely ja informaatiotieteet'},
 {'description': u'Fysiikka', 'name': u'Fysiikka', 'title': u'Fysiikka'},
 {'description': u'Avaruustieteet ja tähtitiede',
  'name': u'Avaruustieteet ja tähtitiede',
  'title': u'Avaruustieteet ja tähtitiede'},
 {'description': u'Kemia', 'name': u'Kemia', 'title': u'Kemia'},
 {'description': u'Maantiede ja ympäristötieteet',
  'name': u'Maantiede ja ympäristötieteet',
  'title': u'Maantiede ja ympäristötieteet'},
 {'description': u'Geotieteet',
  'name': u'Geotieteet',
  'title': u'Geotieteet'},
 {'description': u'Ympäristötiede',
  'name': u'Ympäristötiede',
  'title': u'Ympäristötiede'},
 {'description': u'Biotieteet',
  'name': u'Biotieteet',
  'title': u'Biotieteet'},
 {'description': u'Ekologia, evoluutiobiologia',
  'name': u'Ekologia, evoluutiobiologia',
  'title': u'Ekologia, evoluutiobiologia'},
 {'description': u'Biokemia, solu- ja molekyylibiologia',
  'name': u'Biokemia, solu- ja molekyylibiologia',
  'title': u'Biokemia, solu- ja molekyylibiologia'},
 {'description': u'Kasvibiologia, mikrobiologia, virologia',
  'name': u'Kasvibiologia, mikrobiologia, virologia',
  'title': u'Kasvibiologia, mikrobiologia, virologia'},
 {'description': u'Genetiikka, kehitysbiologia, fysiologia',
  'name': u'Genetiikka, kehitysbiologia, fysiologia',
  'title': u'Genetiikka, kehitysbiologia, fysiologia'},
 {'description': u'Muut luonnontieteet',
  'name': u'Muut luonnontieteet',
  'title': u'Muut luonnontieteet'},
 {'description': u'Arkkitehtuuri',
  'name': u'Arkkitehtuuri',
  'title': u'Arkkitehtuuri'},
 {'description': u'Rakennus- ja yhdyskuntatekniikka',
  'name': u'Rakennus- ja yhdyskuntatekniikka',
  'title': u'Rakennus- ja yhdyskuntatekniikka'},
 {'description': u'Sähkö-, automaatio- ja tietoliikennetekniikka, elektroniikka',
  'name': u'Sähkö-, automaatio- ja tietoliikennetekniikka, elektroniikka',
  'title': u'Sähkö-, automaatio- ja tietoliikennetekniikka, elektroniikka'},
 {'description': u'Kone- ja valmistustekniikka',
  'name': u'Kone- ja valmistustekniikka',
  'title': u'Kone- ja valmistustekniikka'},
 {'description': u'Teknillinen kemia, kemian prosessitekniikka',
  'name': u'Teknillinen kemia, kemian prosessitekniikka',
  'title': u'Teknillinen kemia, kemian prosessitekniikka'},
 {'description': u'Materiaalitekniikka',
  'name': u'Materiaalitekniikka',
  'title': u'Materiaalitekniikka'},
 {'description': u'Lääketieteen tekniikka',
  'name': u'Lääketieteen tekniikka',
  'title': u'Lääketieteen tekniikka'},
 {'description': u'Ympäristötekniikka',
  'name': u'Ympäristötekniikka',
  'title': u'Ympäristötekniikka'},
 {'description': u'Ympäristön bioteknologia',
  'name': u'Ympäristön bioteknologia',
  'title': u'Ympäristön bioteknologia'},
 {'description': u'Teollinen bioteknologia',
  'name': u'Teollinen bioteknologia',
  'title': u'Teollinen bioteknologia'},
 {'description': u'Nanoteknologia',
  'name': u'Nanoteknologia',
  'title': u'Nanoteknologia'},
 {'description': u'Muu tekniikka',
  'name': u'Muu tekniikka',
  'title': u'Muu tekniikka'},
 {'description': u'Peruslääketieteet',
  'name': u'Peruslääketieteet',
  'title': u'Peruslääketieteet'},
 {'description': u'Biolääketieteet',
  'name': u'Biolääketieteet',
  'title': u'Biolääketieteet'},
 {'description': u'Neurotieteet',
  'name': u'Neurotieteet',
  'title': u'Neurotieteet'},
 {'description': u'Kliiniset lääketieteet',
  'name': u'Kliiniset lääketieteet',
  'title': u'Kliiniset lääketieteet'},
 {'description': u'Sisätaudit',
  'name': u'Sisätaudit',
  'title': u'Sisätaudit'},
 {'description': u'Syöpätaudit',
  'name': u'Syöpätaudit',
  'title': u'Syöpätaudit'},
 {'description': u'Naisten- ja lastentaudit',
  'name': u'Naisten- ja lastentaudit',
  'title': u'Naisten- ja lastentaudit'},
 {'description': u'Neurologia ja psykiatria',
  'name': u'Neurologia ja psykiatria',
  'title': u'Neurologia ja psykiatria'},
 {'description': u'Korva-, nenä- ja kurkkutaudit, silmätaudit',
  'name': u'Korva-, nenä- ja kurkkutaudit, silmätaudit',
  'title': u'Korva-, nenä- ja kurkkutaudit, silmätaudit'},
 {'description': u'Kirurgia, anestesiologia, tehohoito, radiologia',
  'name': u'Kirurgia, anestesiologia, tehohoito, radiologia',
  'title': u'Kirurgia, anestesiologia, tehohoito, radiologia'},
 {'description': u'Hammaslääketieteet',
  'name': u'Hammaslääketieteet',
  'title': u'Hammaslääketieteet'},
 {'description': u'Terveystieteet',
  'name': u'Terveystieteet',
  'title': u'Terveystieteet'},
 {'description': u'Terveystiede',
  'name': u'Terveystiede',
  'title': u'Terveystiede'},
 {'description': u'Kansanterveystiede, ympäristö ja työterveys',
  'name': u'Kansanterveystiede, ympäristö ja työterveys',
  'title': u'Kansanterveystiede, ympäristö ja työterveys'},
 {'description': u'Liikuntatiede',
  'name': u'Liikuntatiede',
  'title': u'Liikuntatiede'},
 {'description': u'Hoitotiede',
  'name': u'Hoitotiede',
  'title': u'Hoitotiede'},
 {'description': u'Farmasia', 'name': u'Farmasia', 'title': u'Farmasia'},
 {'description': u'Lääketieteen bioteknologia',
  'name': u'Lääketieteen bioteknologia',
  'title': u'Lääketieteen bioteknologia'},
 {'description': u'Oikeuslääketiede ja muut lääketieteet',
  'name': u'Oikeuslääketiede ja muut lääketieteet',
  'title': u'Oikeuslääketiede ja muut lääketieteet'},
 {'description': u'Maatalous ja metsätieteet',
  'name': u'Maatalous ja metsätieteet',
  'title': u'Maatalous ja metsätieteet'},
 {'description': u'Maataloustiede',
  'name': u'Maataloustiede',
  'title': u'Maataloustiede'},
 {'description': u'Metsätiede',
  'name': u'Metsätiede',
  'title': u'Metsätiede'},
 {'description': u'Kotieläintiede, maitotaloustiede',
  'name': u'Kotieläintiede, maitotaloustiede',
  'title': u'Kotieläintiede, maitotaloustiede'},
 {'description': u'Eläinlääketiede',
  'name': u'Eläinlääketiede',
  'title': u'Eläinlääketiede'},
 {'description': u'Maatalouden bioteknologia',
  'name': u'Maatalouden bioteknologia',
  'title': u'Maatalouden bioteknologia'},
 {'description': u'Muut maataloustieteet',
  'name': u'Muut maataloustieteet',
  'title': u'Muut maataloustieteet'},
 {'description': u'Kansantaloustiede',
  'name': u'Kansantaloustiede',
  'title': u'Kansantaloustiede'},
 {'description': u'Liiketaloustiede',
  'name': u'Liiketaloustiede',
  'title': u'Liiketaloustiede'},
 {'description': u'Oikeustiede',
  'name': u'Oikeustiede',
  'title': u'Oikeustiede'},
 {'description': u'Sosiaalitieteet',
  'name': u'Sosiaalitieteet',
  'title': u'Sosiaalitieteet'},
 {'description': u'Sosiologia',
  'name': u'Sosiologia',
  'title': u'Sosiologia'},
 {'description': u'Sosiaali- ja yhteiskuntapolitiikka',
  'name': u'Sosiaali- ja yhteiskuntapolitiikka',
  'title': u'Sosiaali- ja yhteiskuntapolitiikka'},
 {'description': u'Psykologia',
  'name': u'Psykologia',
  'title': u'Psykologia'},
 {'description': u'Kasvatustieteet',
  'name': u'Kasvatustieteet',
  'title': u'Kasvatustieteet'},
 {'description': u'Valtio-oppi, hallintotiede',
  'name': u'Valtio-oppi, hallintotiede',
  'title': u'Valtio-oppi, hallintotiede'},
 {'description': u'Media- ja viestintätieteet',
  'name': u'Media- ja viestintätieteet',
  'title': u'Media- ja viestintätieteet'},
 {'description': u'Yhteiskuntamaantiede, talousmaantiede',
  'name': u'Yhteiskuntamaantiede, talousmaantiede',
  'title': u'Yhteiskuntamaantiede, talousmaantiede'},
 {'description': u'Muut yhteiskuntatieteet',
  'name': u'Muut yhteiskuntatieteet',
  'title': u'Muut yhteiskuntatieteet'},
 {'description': u'Filosofia', 'name': u'Filosofia', 'title': u'Filosofia'},
 {'description': u'Kielitieteet, kirjallisuus',
  'name': u'Kielitieteet, kirjallisuus',
  'title': u'Kielitieteet, kirjallisuus'},
 {'description': u'Kielitieteet',
  'name': u'Kielitieteet',
  'title': u'Kielitieteet'},
 {'description': u'Kirjallisuuden tutkimus',
  'name': u'Kirjallisuuden tutkimus',
  'title': u'Kirjallisuuden tutkimus'},
 {'description': u'Taiteiden tutkimus',
  'name': u'Taiteiden tutkimus',
  'title': u'Taiteiden tutkimus'},
 {'description': u'Teatteri, tanssi, musiikki, muut esittävät taiteet',
  'name': u'Teatteri, tanssi, musiikki, muut esittävät taiteet',
  'title': u'Teatteri, tanssi, musiikki, muut esittävät taiteet'},
 {'description': u'Kuvataide ja muotoilu',
  'name': u'Kuvataide ja muotoilu',
  'title': u'Kuvataide ja muotoilu'},
 {'description': u'Teologia', 'name': u'Teologia', 'title': u'Teologia'},
 {'description': u'Historia ja arkeologia',
  'name': u'Historia ja arkeologia',
  'title': u'Historia ja arkeologia'},
 {'description': u'Muut humanistiset tieteet',
  'name': u'Muut humanistiset tieteet',
  'title': u'Muut humanistiset tieteet'},
 {'description': u'Muut', 'name': u'Muut', 'title': u'Muut'}]
