'''
Kata tests
'''


def create_validator_test_data():
    '''
    This is some test data from Add dataset.
    '''

    return {
        ('__extras',): {'_ckan_phase': u'',
                        'evdescr': [],
                        'evwhen': [],
                        'evwho': [],
                        'groups': [],
                        'pkg_name': u''},
        ('access',): u'contact',
        ('accessRights',): u'',
        ('accessrequestURL',): u'',
        ('algorithm',): u'',
        ('author', 0, 'value'): u'dada',
        ('checksum',): u'',
        ('contactURL',): u'http://google.com',
        ('discipline',): u'',
        ('evtype', 0, 'value'): u'collection',
        ('extras',): [{'key': 'funder', 'value': u''},
                        {'key': 'discipline', 'value': u''},
                        {'key': 'publisher', 'value': u'dada'},
                        {'key': 'fformat', 'value': u''},
                        {'key': 'project_funding', 'value': u''},
                        {'key': 'project_homepage', 'value': u''},
                        {'key': 'owner', 'value': u'dada'},
                        {'key': 'version', 'value': u'2013-08-14T10:37:09Z'},
                        {'key': 'temporal_coverage_begin', 'value': u''},
                        {'key': 'accessrequestURL', 'value': u''},
                        {'key': 'phone', 'value': u'+35805050505'},
                        {'key': 'licenseURL', 'value': u'dada'},
                        {'key': 'geographic_coverage', 'value': u''},
                        {'key': 'access', 'value': u'contact'},
                        {'key': 'algorithm', 'value': u''},
                        {'key': 'langdis', 'value': u'True'},
                        {'key': 'accessRights', 'value': u''},
                        {'key': 'contactURL', 'value': u'http://google.com'},
                        {'key': 'project_name', 'value': u''},
                        {'key': 'checksum', 'value': u''},
                        {'key': 'temporal_coverage_end', 'value': u''},
                        {'key': 'projdis', 'value': u'True'},
                        {'key': 'language', 'value': u''}],
        ('fformat',): u'',
        ('funder',): u'',
        ('geographic_coverage',): u'',
        ('langdis',): u'False',
        ('language',): u'swe',
        ('licenseURL',): u'dada',
        ('license_id',): u'',
        ('log_message',): u'',
        ('name',): u'',
        ('notes',): u'',
        ('organization', 0, 'value'): u'dada',
        ('owner',): u'dada',
        ('phone',): u'+35805050505',
        ('maintainer_email',): u'kata.selenium@gmail.com',
        ('projdis',): u'True',
        ('project_funding',): u'',
        ('project_homepage',): u'',
        ('project_name',): u'',
        ('publisher',): u'dada',
        ('save',): u'finish',
        ('tag_string',): u'dada',
        ('temporal_coverage_begin',): u'',
        ('temporal_coverage_end',): u'',
        ('title', 0, 'lang'): u'sv',
        ('title', 0, 'value'): u'dada',
        ('type',): None,
        ('version',): u'2013-08-14T10:37:09Z',
        ('versionPID',): u''}

